<?php
/*
 * Copyright (c) 2026 bbecker
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */


$labels["enable_in_compose_view"] = "Aktiviere Mailmerge in der Verfassenansicht";
$labels["send_drafts"] = "Sende Entwürfe";
$labels["send_drafts_tooltip"] = "Sende alle Entwürfe in aktullem Ordner oder Suchergebnis";
$labels["send_selected"] = "Senden";
$labels["send_selected_tooltip"] = "Sende alle ausgewählten Nachrichten";

$labels["mailmerge_options"] = "Mailmerge Optionen";

$labels["separator"] = "Feld-Trennzeichen";
$labels["comma"] = ", (Komma)";
$labels["semicolon"] = "; (Semikolon)";
$labels["pipe"] = "| (Senkrechter Strich)";
$labels["tab"] = "Tab";

$labels["field_enclosure"] = "Feld-Begrenzungszeichen";
$labels["double_quotes"] = "\" (Doppel Anführungszeichen)";
$labels["single_quotes"] = "' (Einzel Anführungszeichen)";

$labels["file_encoding"] = "Datei Kodierung";

$labels["generation_behavior"] = "Erstellungsverhalten";
$labels["generate_all"] = "Alle Erstellen";
$labels["generate_rcpt"] = "Erstelle nur mit mindestens ein:r Empfänger:in (An, Cc oder Bcc)";
$labels["generate_to"] = "Erstelle nur mit An";
$labels["generate_non_empty"] = "Überspringe bei beliebigem leeren Empfänger:innen-Platzhalter";

$labels["mailmerge"] = "Mailmerge";

$labels["save_to_folder"] = "Speichere in Ordner";

$labels["sent_messages"] = "\$success gesendet. \$fail fehlgeschlagen";

$labels["no_csv_selected"] = "Es wurde keine CSV Datei ausgewählt!";