<?php
/*
 * Copyright (c) 2026 bbecker
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */


$labels["enable_in_compose_view"] = "Enable Mailmerge in Compose view";
$labels["send_drafts"] = "Send Drafts";

$labels["mailmerge_options"] = "Mailmerge Options";

$labels["separator"] = "Separator";
$labels["comma"] = ", (Comma)";
$labels["semicolon"] = "; (Semicolon)";
$labels["pipe"] = "| (Pipe)";
$labels["tab"] = "Tab";

$labels["field_enclosure"] = "Field Enclosure";
$labels["double_quotes"] = "\" (Double Quotes)";
$labels["single_quotes"] = "' (Single Quote)";

$labels["file_encoding"] = "File Encoding";

$labels["generation_behavior"] = "Generation Behavior";
$labels["generate_all"] = "Generate All";
$labels["generate_rcpt"] = "Generate only with at least one Recipient (To, CC or Bcc)";
$labels["generate_to"] = "Generate only with To";
$labels["generate_non_empty"] = "Skip on any empty recipient placeholder";

$labels["mailmerge"] = "Mailmerge";

$labels["save_to_folder"] = "Save to folder";

$labels["sent_messages"] = "sent \$success messages. \$fail failed";

$labels["no_csv_selected"] = "No CSV File was selected!";